### ISSUE TITLE
Consider titles

### ISSUE THREAD

**Issue by afomi** [rebeccawilliams/bookclub#9]
* Gardens of Democracy - Eric Liu
* Systems Thinking - Donella Meadows
* See what I mean - Kevin Cheng

**Comment by afomi** [comment]
found - http://civictechbook.club/readinglist. can submit PR.

**Comment by rebeccawilliams** [comment]
Added first two to Bookshop list: https://bookshop.org/lists/civic-tech-book-club-reading-list

If still interested can you submit PR to reading list for the Cheng piece?
